zemi/src/main/java/syain/entity/Notification.java
package syain.entity;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Notificationエンティティクラス
 * 
 */
@Entity
@Generated(value = { "S2JDBC-Gen 2.4.46",
		"org.seasar.extension.jdbc.gen.internal.model.EntityModelFactoryImpl" }, date = "2016/05/30 11:58:24")
public class Notification implements Serializable {

	private static final long serialVersionUID = 1L;

	/** notification_codeプロパティ */
	@Id
	@GeneratedValue
	@Column(nullable = false, unique = true)
    public Integer notification_code;

	/** notification_genre_idプロパティ */
	@Column(length = 50, nullable = false, unique = false)
	public String notification_genre_code;

	/** notification_titleプロパティ */
	@Column(length = 10, nullable = false, unique = false)
	public String notification_title;

	/** notification_contentプロパティ */
	@Column(length = 1, nullable = true, unique = false)
	public String notification_content;

	/** published_dayプロパティ */
	@Column(length = 50, nullable = false, unique = false)
	public String published_day;

	/** publisher_flgプロパティ */
	@Column(length = 50, nullable = false, unique = false)
	public String published_flg;

	/** publisher_flgで非表示にするプロパティ */
	public String getPublished_flgLabel() {
		if (published_flg.equals("0")) {
			return "公開";
		} else {
			return "非公開";
		}
	}
	
	/** notification_genre_codeで表示を変えるプロパティ*/
	public String getNotification_genre_codeLabel() {
		if (notification_genre_code.equals("01")) {
			return "事務";
		} else if (notification_genre_code.equals("02")){
			return "教務";
		} else if (notification_genre_code.equals("03")){
			return "奨学金";
		} else if (notification_genre_code.equals("09")){
			return "その他";
		} else {
		return "";
		}
	}
}

zemi/src/main/java/syain/form/NotificationForm.java
package syain.form;


import org.seasar.struts.annotation.Maxlength;
import org.seasar.struts.annotation.Required;

public class NotificationForm {
	
	@Maxlength(maxlength=50)
	public String notification_code;
	
	@Maxlength(maxlength=50)
	public String notification_genre_code;
	
	@Required
	@Maxlength(maxlength=50)
	public String notification_title;
	
	@Required
	@Maxlength(maxlength=500)
	public String notification_content;
	
	@Maxlength(maxlength=50)
	public String published_day;
	
	@Maxlength(maxlength=50)
	public String published_flg;
}

zemi/src/main/java/syain/action/NotificationAction.java
package syain.action;

import java.util.List;
import java.util.Date;
import java.text.SimpleDateFormat;

import javax.annotation.Resource;

import org.seasar.struts.annotation.ActionForm;
import org.seasar.struts.annotation.Execute;

import syain.dto.NotificationDto;
import syain.entity.Notification;
import syain.form.NotificationForm;
import syain.service.NotificationService;

public class NotificationAction {
	
	public List<Notification> notificationList;
	public List<Notification> notificationSideList;
	public Notification notification;
	
	Date date = new Date();
	SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
	 
	@Resource
	protected NotificationService notificationService;

	@Resource
	@ActionForm
	protected NotificationForm notificationForm;

	@Resource
	protected NotificationDto notificationDto;
	
	@Execute(validator = false)
   	public String notification(){
		notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderById(notificationForm.published_flg);
   	return "notification.jsp";
    }
	
	@Execute(validator = false)
   	public String notification1(){
		notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdPast1(notificationForm.published_flg,notificationForm.published_day);
   	return "notification.jsp";
    }
	
	@Execute(validator = false)
   	public String notification2(){
		notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdPast2(notificationForm.published_flg,notificationForm.published_day);
   	return "notification.jsp";
    }
	
	@Execute(validator = false)
   	public String notification3(){
		notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdPast3(notificationForm.published_flg,notificationForm.published_day);
   	return "notification.jsp";
    }
	
	@Execute(validator = false)
   	public String notification4(){
		notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdPast4(notificationForm.published_flg,notificationForm.published_day);
   	return "notification.jsp";
    }
	
	@Execute(validator = false)
   	public String notification5(){
		notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdPast5(notificationForm.published_flg,notificationForm.published_day);
   	return "notification.jsp";
    }
	
	/* お知らせ管理者用 */
    @Execute(validator = false)
    	public String notification_admin() {
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdAdmin();
    	return "notification_admin.jsp";
    }
    
    /*お知らせ新規登録*/
    @Execute(validator = false)
   	public String notification_ins(){
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
    	notificationList = notificationService.findAllOrderById(notificationForm.published_flg);
   	return "notification_ins.jsp";
    }
    
    @Execute(validator = true,input="notification_ins.jsp")
	public String notification_ins_fin() {
		notificationDto.setNotification_code(notificationForm.notification_code);
		notificationDto.setNotification_genre_code(notificationForm.notification_genre_code);
		notificationDto.setNotification_title(notificationForm.notification_title);
		notificationDto.setNotification_content(notificationForm.notification_content);
		notificationDto.setPublished_day(sdf1.format(date));
		notificationDto.setPublished_flg("0");
		notificationService.insert(notificationDto);
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdAdmin();
	return "notification_admin.jsp";
    }
    
	/*お知らせ更新 */
	@Execute(validator = false)
   	public String notification_upd(){
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notification = notificationService.findById(notificationForm.notification_code);
		notificationDto.setNotification_code(String.valueOf(notificationForm.notification_code));
		notificationDto.setNotification_genre_code(notificationForm.notification_genre_code);
		notificationDto.setNotification_title(notificationForm.notification_title);
		notificationDto.setNotification_content(notificationForm.notification_content);
		notificationDto.setPublished_day(sdf1.format(date));
		notificationDto.setPublished_flg(notificationForm.published_flg);
   	return "notification_upd.jsp";
    }
	
	@Execute(validator = true,input="notification_upd.jsp")
	public String notification_upd_fin() {
		notificationDto.setNotification_code(notificationForm.notification_code);
		notificationDto.setNotification_genre_code(notificationForm.notification_genre_code);
		notificationDto.setNotification_title(notificationForm.notification_title);
		notificationDto.setNotification_content(notificationForm.notification_content);
		notificationDto.setPublished_day(sdf1.format(date));
		notificationDto.setPublished_flg(notificationForm.published_flg);
		notificationService.update(notificationDto);
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdAdmin();
	return "notification_admin.jsp";
    }
	
	/* お知らせ削除 */
	@Execute(validator = true,input="notification_admin.jsp")
   	public String notification_del(){
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
    	notificationDto.setNotification_code(notificationForm.notification_code);
		notificationDto.setNotification_genre_code(notificationForm.notification_genre_code);
		notificationDto.setNotification_title(notificationForm.notification_title);
		notificationDto.setNotification_content(notificationForm.notification_content);
		notificationDto.setPublished_day(sdf1.format(date));
		notificationDto.setPublished_flg(notificationForm.published_flg);
   	return "notification_del.jsp";
    }
	
	@Execute(validator = true,input="notification_upd.jsp")
	public String notification_del_fin() {
		notificationDto.setNotification_code(notificationForm.notification_code);
		notificationDto.setNotification_genre_code(notificationForm.notification_genre_code);
		notificationDto.setNotification_title(notificationForm.notification_title);
		notificationDto.setNotification_content(notificationForm.notification_content);
		notificationDto.setPublished_day(sdf1.format(date));
		notificationDto.setPublished_flg(notificationForm.published_flg);
		notificationService.delete(notificationDto);
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderByIdAdmin();
	return "notification_admin.jsp";
    }
	
	/* お知らせ詳細*/
	@Execute(validator = false)
   	public String notification_detail(){
    	notificationSideList= notificationService.findAllOrderById(notificationForm.published_flg);
		notificationList = notificationService.findAllOrderById(notificationForm.published_flg);
		notificationDto.setNotification_code(notificationForm.notification_code);
		notificationDto.setNotification_genre_code(notificationForm.notification_genre_code);
		notificationDto.setNotification_title(notificationForm.notification_title);
		notificationDto.setNotification_content(notificationForm.notification_content);
		notificationDto.setPublished_day(sdf1.format(date));
		notificationDto.setPublished_flg(notificationForm.published_flg);
   	return "notification_detail.jsp";
    }
}

zemi/src/main/webapp/WEB-INF/view/notification/notification.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html ng-app="myApp">
<html lang="ja">
<head>
<meta charset="UTF-8">
<title></title>
<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>
	$(function() {
		var $setElm = $('td a');
		var cutFigure = '10'; // カットする文字数
		var afterTxt = ' …'; // 文字カット後に表示するテキスト

		$setElm.each(function() {
			var textLength = $(this).text().length;
			var textTrim = $(this).text().substr(0, (cutFigure))

			if (cutFigure < textLength) {
				$(this).html(textTrim + afterTxt).css({
					visibility : 'visible'
				});
			} else if (cutFigure >= textLength) {
				$(this).css({
					visibility : 'visible'
				});
			}
		});
	});
</script>
</head>
<body>
	<tiles:insert template="/WEB-INF/view/common/layout3.jsp" flush="true">
		<tiles:put name="title" value="Hello SAStruts!" />
		<tiles:put name="content" type="string">
			<link rel="stylesheet"
				href="${f:url('/css/jquery.dataTables.min.css')}" />
			<script src="${f:url('/js/jquery.dataTables.min.js')}"></script>
			<script src="${f:url('/js/dataTable_sub.js')}"></script>
			<article>
				<h3>お知らせ</h3>
				<html:errors />
				<s:form method="POST">
					<table class="dataTable" id="syain_table">
						<thead>
							<tr>
								<th>掲載日</th>
								<th>ジャンル</th>
								<th>お知らせタイトル</th>
								<th>お知らせ内容</th>
							</tr>
						</thead>
						<tbody>
							<c:forEach var="notification" varStatus="c"
								items="${notificationList}">
								<tr>
									<td>${f:h(notification.published_day)}</td>
									<td>${f:h(notification.notification_genre_codeLabel)}</td>
									<td><s:link
											href="notification_detail?notification_code=${f:h(notification.notification_code)}&notification_genre_code=${f:h(notification.notification_genre_code)}&notification_title=${f:h(notification.notification_title)}&notification_content=${f:h(notification.notification_content)}
											&published_day=${f:h(notification.published_day)}&published_flg=${f:h(notification.published_flg)}">${f:h(notification.notification_title)}</s:link></td>
									<td><s:link
											href="notification_detail?notification_code=${f:h(notification.notification_code)}&notification_genre_code=${f:h(notification.notification_genre_code)}&notification_title=${f:h(notification.notification_title)}&notification_content=${f:h(notification.notification_content)}
											&published_day=${f:h(notification.published_day)}&published_flg=${f:h(notification.published_flg)}">${f:h(notification.notification_content)}</s:link></td>
								</tr>
							</c:forEach>
						</tbody>
					</table>
				</s:form>
			</article>
		</tiles:put>
	</tiles:insert>
</body>
</html>

zemi/src/main/webapp/WEB-INF/view/notification/notification_admin.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title></title>
<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>
	$(function() {
		var $setElm = $('td');
		var cutFigure = '10'; // カットする文字数
		var afterTxt = ' …'; // 文字カット後に表示するテキスト

		$setElm.each(function() {
			var textLength = $(this).text().length;
			var textTrim = $(this).text().substr(0, (cutFigure))

			if (cutFigure < textLength) {
				$(this).html(textTrim + afterTxt).css({
					visibility : 'visible'
				});
			} else if (cutFigure >= textLength) {
				$(this).css({
					visibility : 'visible'
				});
			}
		});
	});
</script>
</head>
<body>
	<tiles:insert template="/WEB-INF/view/common/layout3.jsp" flush="true">
		<tiles:put name="title" value="Hello SAStruts!" />
		<tiles:put name="content" type="string">
			<link rel="stylesheet"
				href="${f:url('/css/jquery.dataTables.min.css')}" />
			<script src="${f:url('/js/jquery.dataTables.min.js')}"></script>
			<script src="${f:url('/js/dataTable_sub.js')}"></script>
			<article>
				<h3>お知らせ管理者用</h3>
				<html:errors />
				<s:form method="POST">
					<div Align="right">
						<s:link href="notification_ins">新規作成</s:link>
					</div>
					<table class="dataTable" id="syain_table">
						<thead>
							<tr>
								<th>掲載日</th>
								<th>ジャンル</th>
								<th>お知らせタイトル</th>
								<th>編集</th>
								<th>削除</th>
							</tr>
						</thead>
						<tbody>
							<c:forEach var="notification" varStatus="c"
								items="${notificationList}">
								<tr>
									<td>${f:h(notification.published_day)}</td>
									<td>${f:h(notification.notification_genre_codeLabel)}</td>
									<td>${f:h(notification.notification_title)}</td>
									<html:hidden property="notification_code"
										value="${f:h(notification.notification_code)}" />
									<html:hidden property="notification_genre_code"
										value="${f:h(notification.notification_genre_code)}" />
									<html:hidden property="notification_title"
										value="${f:h(notification.notification_title)}" />
									<html:hidden property="notification_content"
										value="${f:h(notification.notification_content)}" />
									<html:hidden property="published_day"
										value="${f:h(notification.published_day)}" />
									<html:hidden property="published_flg"
										value="${f:h(notification.published_flg)}" />
									<td><s:link
											href="notification_upd?notification_code=${f:h(notification.notification_code)}&notification_genre_code=${f:h(notification.notification_genre_code)}&notification_title=${f:h(notification.notification_title)}&notification_content=${f:h(notification.notification_content)}
									&published_day=${f:h(notification.published_day)}&published_flg=${f:h(notification.published_flg)}">編集</s:link></td>
									<td><s:link
											href="notification_del?notification_code=${f:h(notification.notification_code)}&notification_genre_code=${f:h(notification.notification_genre_code)}&notification_title=${f:h(notification.notification_title)}&notification_content=${f:h(notification.notification_content)}
									&published_day=${f:h(notification.published_day)}&published_flg=${f:h(notification.published_flg)}">削除</s:link></td>
								</tr>
							</c:forEach>
						</tbody>
					</table>
				</s:form>
			</article>
		</tiles:put>
	</tiles:insert>
</body>
</html>

zemi/src/main/webapp/WEB-INF/view/notification/notification_del.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title></title>
</head>
<body>
	<tiles:insert template="/WEB-INF/view/common/layout3.jsp" flush="true">
		<tiles:put name="title" value="Hello SAStruts!" />
		<tiles:put name="content" type="string">
					<link rel="stylesheet"
				href="${f:url('/css/jquery.dataTables.min.css')}" />
			<script src="${f:url('/js/jquery.dataTables.min.js')}"></script>
			<script src="${f:url('/js/dataTable_sub.js')}"></script>
			<article>
				<h3>お知らせ削除</h3>
				<html:errors />
				<s:form method="POST">
					<html:hidden property="notification_code"
						value="${f:h(notification_code)}" />
					<html:hidden property="notification_genre_code"
						value="${f:h(notification_genre_code)}" />
					<html:hidden property="notification_title"
						value="${f:h(notification_title)}" />
					<html:hidden property="notification_content"
						value="${f:h(notification_content)}" />
					<html:hidden property="published_day" value="${f:h(published_day)}" />
					<html:hidden property="published_flg" value="${f:h(published_flg)}" />
					<table class="basetable" id="syain_table">
						<tr>
							<th>タイトル</th>
							<td>${f:h(notification_title)}</td>
						</tr>
						<tr>
							<th>内容</th>
							<td>${f:h(notification_content)}</td>
						</tr>
					</table>
					<br>
					<div Align="center">
						<s:submit property="notification_del_fin" value="削除"
							styleClass="button" />
						<s:submit property="notification_admin" value="戻る"
							styleClass="button" />
					</div>
				</s:form>
			</article>
		</tiles:put>
	</tiles:insert>
</body>
</html>

zemi/src/main/webapp/WEB-INF/view/notification/notification_detail.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title></title>
</head>
<body>
	<tiles:insert template="/WEB-INF/view/common/layout3.jsp" flush="true">
		<tiles:put name="title" value="Hello SAStruts!" />
		<tiles:put name="content" type="string">
					<link rel="stylesheet"
				href="${f:url('/css/jquery.dataTables.min.css')}" />
			<script src="${f:url('/js/jquery.dataTables.min.js')}"></script>
			<script src="${f:url('/js/dataTable_sub.js')}"></script>
			<article>
				<h3>お知らせ詳細</h3>
				<html:errors />
				<s:form method="POST">
					<table class="basetable" id="syain_table">
					<tr>
							<th>掲載日</th>
							<td>${f:h(published_day)}</td>
						</tr>
						<tr>
							<th>タイトル</th>
							<td>${f:h(notification_title)}</td>
						</tr>
						<tr>
							<th>内容</th>
							<td>${f:h(notification_content)}</td>
						</tr>
					</table>
					<br>
					<div Align="center">
						<s:submit property="notification" value="お知らせ一覧へ"
							styleClass="button" />
					</div>
				</s:form>
			</article>
		</tiles:put>
	</tiles:insert>
</body>
</html>

zemi/src/main/webapp/WEB-INF/view/notification/notification_ins.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title></title>
</head>
<body>
	<tiles:insert template="/WEB-INF/view/common/layout3.jsp" flush="true">
		<tiles:put name="title" value="Hello SAStruts!" />
		<tiles:put name="content" type="string">
					<link rel="stylesheet"
				href="${f:url('/css/jquery.dataTables.min.css')}" />
			<script src="${f:url('/js/jquery.dataTables.min.js')}"></script>
			<script src="${f:url('/js/dataTable_sub.js')}"></script>
			<article>
				<h3>お知らせ新規登録</h3>
				<html:errors />
				<s:form method="POST">
					<table class="basetable" id="syain_table">
						<tr>
							<th>ジャンル</th>
							<td><html:select property="notification_genre_code"
									styleClass="tblInput">
									<html:option value="01">事務</html:option>
									<html:option value="02">教務</html:option>
									<html:option value="03">奨学金</html:option>
									<html:option value="09">その他</html:option>
								</html:select></td>
						</tr>
						<tr>
							<th>タイトル</th>
							<td><html:text property="notification_title" size="47"
									styleClass="tblInput" value="" /></td>
						</tr>
						<tr>
							<th>内容</th>
							<td><html:textarea property="notification_content" cols="47"
									rows="10" styleClass="tblInput" value="" /></td>
						</tr>
					</table>
					<br>
					<div Align="center">
						<s:submit property="notification_ins_fin" value="登録"
							styleClass="button" />
						<span style="margin-right: 1em;"></span>
						<s:submit property="notification_admin" value="戻る"
							styleClass="button" />
					</div>
				</s:form>
			</article>
		</tiles:put>
	</tiles:insert>
</body>
</html>

zemi/src/main/webapp/WEB-INF/view/notification/notification_upd.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title></title>
</head>
<body>
	<tiles:insert template="/WEB-INF/view/common/layout3.jsp" flush="true">
		<tiles:put name="title" value="Hello SAStruts!" />
		<tiles:put name="content" type="string">
					<link rel="stylesheet"
				href="${f:url('/css/jquery.dataTables.min.css')}" />
			<script src="${f:url('/js/jquery.dataTables.min.js')}"></script>
			<script src="${f:url('/js/dataTable_sub.js')}"></script>
			<article>
				<h3>お知らせ更新</h3>
				<html:errors />
				<s:form method="POST">
					<html:hidden property="notification_code"
						value="${f:h(notification_code)}" />
					<html:hidden property="published_day" value="${f:h(published_day)}" />
					<table class="basetable" id="syain_table">
					<tr>
							<th>ジャンル</th>
							<td><html:select property="notification_genre_code"
									styleClass="tblInput">
									<html:option value="01">事務</html:option>
									<html:option value="02">教務</html:option>
									<html:option value="03">奨学金</html:option>
									<html:option value="09">その他</html:option>
								</html:select></td>
						</tr>
						<tr>
							<th>タイトル</th>
							<td><html:text property="notification_title" size="47"
									styleClass="tblInput" value="${f:h(notification_title)}" /></td>
						</tr>
						<tr>
							<th>内容</th>
							<td><html:textarea property="notification_content" cols="47"
									rows="10" styleClass="tblInput"
									value="${f:h(notification_content)}" /></td>
						</tr>
						<tr>
							<th>公開する？</th>
							<td><html:select property="published_flg"
									styleClass="tblInput">
									<html:option value="0">公開</html:option>
									<html:option value="1">非公開</html:option>
								</html:select></td>
						</tr>
					</table>
					<br>
					<div Align="center">
						<s:submit property="notification_upd_fin" value="更新"
							styleClass="button" />
						<span style="margin-right: 1em;"></span>	
						<s:submit property="notification_admin" value="戻る"
							styleClass="button" />
					</div>
				</s:form>
			</article>
		</tiles:put>
	</tiles:insert>
</body>
</html>